### ISSUE TITLE
Continuous reindexing from scratch after an error: CRITICAL Error: Call to a member function getValues() on null in ...

### ISSUE THREAD

**Issue by Wolvverine** [zobo/vscode-php-intellisense#61]
Continuous reindexing from scratch after an error:
```
...
[Trace - 12:07:21 AM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "Parsing file:///e:/users/USERNAME/Projects/GitHub/glpi/vendor/andrewsville/php-token-reflection/tests/data/parseerror/invalid-class-4.php"
}

Parsing file:///e:/users/USERNAME/Projects/GitHub/glpi/vendor/andrewsville/php-token-reflection/tests/data/parseerror/invalid-class-4.php
CRITICAL  Error: Call to a member function getValues() on null in C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\DefinitionResolver.php:246
Stack trace:
#0 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(158): LanguageServer\DefinitionResolver->createDefinitionFromNode()
#1 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(125): LanguageServer\TreeAnalyzer->collectDefinitionsAndReferences()
#2 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(137): LanguageServer\TreeAnalyzer->traverse()
#3 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\TreeAnalyzer.php(58): LanguageServer\TreeAnalyzer->traverse()
#4 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(147): LanguageServer\TreeAnalyzer->__construct()
#5 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocument.php(105): LanguageServer\PhpDocument->updateContent()
#6 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(130): LanguageServer\PhpDocument->__construct()
#7 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\src\PhpDocumentLoader.php(115): LanguageServer\PhpDocumentLoader->create()
#8 [internal function]: LanguageServer\PhpDocumentLoader->LanguageServer\{closure}()
#9 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\coroutine.php(75): Generator->send()
#10 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\Promise.php(235): Sabre\Event\{closure}()
#11 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(234): Sabre\Event\Promise->Sabre\Event\{closure}()
#12 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(192): Sabre\Event\Loop\Loop->runNextTicks()
#13 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\Loop.php(173): Sabre\Event\Loop\Loop->tick()
#14 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\sabre\event\lib\Loop\functions.php(102): Sabre\Event\Loop\Loop->run()
#15 C:\Users\USERNAME\.vscode\extensions\zobo.php-intellisense-1.1.3\vendor\felixfbecker\language-server\bin\php-language-server.php(59): Sabre\Event\Loop\run()
#16 {main}

[Info  - 12:07:21 AM] Connection to server got closed. Server will restart.
Language server exited with exit code 0
DEBUG     Checking PHPLS_ALLOW_XDEBUG
DEBUG     The Xdebug extension is not loaded

[Trace - 12:07:21 AM] Sending request 'initialize - (0)'.
Params: {
    "processId": 22388,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.80.1"
    },
...
```

**Platform and version**
Windows 10
1.1.3

after delete file "e:/users/USERNAME/Projects/GitHub/glpi/vendor/andrewsville/php-token-reflection/tests/data/parseerror/invalid-class-4.php" loop ended.

**Comment by zobo** [comment]
Thanks for the report, will look in to the error.

**Comment by zobo** [comment]
First part of the fix https://github.com/zobo/php-language-server/pull/56

**Comment by zobo** [comment]
Version 1.1.4 should fix the issue. Please let me know if it's ok now.
